default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 80

development:
  <<: *default
  database: dapper-homework-dev
  username: <%= ENV.fetch('LOCAL_PG_ADMIN_USER') %>
  password: <%= ENV.fetch('LOCAL_PG_ADMIN_PW') %>

test:
  <<: *default
  database: dapper-homework-test
  username: <%= ENV.fetch('LOCAL_PG_ADMIN_USER') %>
  password: <%= ENV.fetch('LOCAL_PG_ADMIN_PW') %>

production:
  <<: *default
  database: dapper-homework-prod
