=begin
Peter Bardon

Dapper Labs Homework Assignment

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
Rails.application.routes.draw do

  mount Rswag::Api::Engine => '/api-docs'
  mount Rswag::Ui::Engine => '/api-docs'
  def add_openapi_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_openapi_route 'POST', '/api/v1/login', controller_name: 'login', action_name: 'create'
  add_openapi_route 'POST', '/api/v1/signup', controller_name: 'signup', action_name: 'create'
  add_openapi_route 'GET', '/api/v1/users', controller_name: 'users', action_name: 'index'
  add_openapi_route 'PUT', '/api/v1/users/{id}', controller_name: 'users', action_name: 'update_user'
end
