=begin
Peter Bardon

Dapper Labs Homework Assignment

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "login".pluralize.to_sym, id: false do |t|
      t.string :email
      t.timestamps
    end

    create_table "token".pluralize.to_sym, id: false do |t|
      t.string :token

      t.timestamps
    end

    create_table "user".pluralize.to_sym, id: false do |t|
      t.string :email
      t.string :first_name
      t.string :last_name

      t.timestamps
    end

  end
end
