=begin
Peter Bardon

Dapper Labs Homework Assignment

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class LoginController < ApplicationController

  def create
    unless params[:email]
      render json: { error: 'missing email' }, status: :bad_request
      return
    end

    unless params[:password]
      render json: { error: 'missing password' }, status: :bad_request
      return
    end

    token = User.authenticate(params[:email], params[:password])

    unless token
      render json: { error: 'failed to generate token' }, status: :server_error
      return
    end

    unless User.find_by_email(params[:email]).valid_token?(token)
      render json: { error: 'invalid token' }, status: :unauthorized
      return
    end

    render json: { token: token }
  end

  def login_params
    params.permit(:email, :password)
  end
end
