=begin
Peter Bardon

Dapper Labs Homework Assignment

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class LoginController < ApplicationController
  def create
    unless login_params[:email]
      render json: { error: 'missing email' }, status: :bad_request
      return
    end

    unless login_params[:password]
      render json: { error: 'missing password' }, status: :bad_request
      return
    end

    token = User.authenticate(login_params)

    unless token
      render json: { error: 'failed to generate token' }, status: :unauthorized
      return
    end

    # Log the login for the user in the database
    Login.create({ email: login_params[:email] })

    render json: { token: token }
  end

  def login_params
    params.permit(:email, :password)
  end
end
