=begin
Peter Bardon

Dapper Labs Homework Assignment

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class SignupController < ApplicationController
  def create
    unless params[:email]
      render json: { error: 'missing email address' }, status: :bad_request
      return
    end

    unless params[:password]
      render json: { error: 'missing password' }, status: :bad_request
      return
    end

    user = User.create_with_password(params[:email], params[:password])

    user.first_name = params[:firstName]
    user.last_name = params[:lastName]

    user.save

    render json: { token: Token.create_token(user.id) }
  end

  def signup_params
    params.permit(:email, :password, :firstName, :lastName)
  end
end
