=begin
Peter Bardon

Dapper Labs Homework Assignment

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class SignupController < ApplicationController
  def create
    unless signup_params[:email]
      render json: { error: 'missing email address' }, status: :bad_request
      return
    end

    unless signup_params[:password]
      render json: { error: 'missing password' }, status: :bad_request
      return
    end

    user_token = User.create_with_password(signup_params)
    unless user_token
      render json: { error: 'failed to create user' }, status: :server_error
      return
    end

    render json: { token: user_token }
  end

  def signup_params
    params.permit(:email, :password, :firstName, :lastName)
  end
end
