=begin
Peter Bardon

Dapper Labs Homework Assignment

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class UsersController < ApplicationController

  def index
    # Your code here
    return unless Token.valid_token?(request.headers['x-authentication-token'])
    
    render json: { users: User.all.map{ |user| { email: user.email, firstName: user.first_name, lastName: user.lastName } } }
  end

  def update_user
    # Your code here
    return unless Token.valid_token?(request.headers['x-authentication-token'])

    user = Token.find_by_token(request.headers['x-authentication-token']).user

    return unless user.valid_user_token?(request.headers['x-authentication-token'])

    user.update({ first_name: user_params[:firstName], last_name: user_params[:lastName] })

    render json: { firstName: user.first_name, lastName: user.last_name }
  end

  def user_params
    params.permit(:firstName, :lastName)
  end
end
