=begin
Peter Bardon

Dapper Labs Homework Assignment

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :tokens, dependent: :destroy

  has_secure_password

  def self.authenticate(params)
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      Token.create_token(user.id)
    end
  end

  def self.create_with_password(params)
    user_id = User.create({ 
      email: params[:email],
      first_name: params[:firstName],
      last_name: params[:lastName],
      password: params[:password]
    }).id
    Token.create_token(user_id)
  end

  def valid_user_token?(token)
    token = Token.find_by(token: token)
    decoded = JWT.decode(token.token, ENV['JWT_SECRET'], true, algorithm: 'HS256')
    decoded[0]['user_id'] == self.id
  end
end
